# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Helper utility to get temporary credentials from AWS SSO"
  homepage "https://leebriggs.co.uk"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.1.0/aws-sso-creds-v1.1.0-darwin-amd64.tar.gz"
    sha256 "13cfa9f6c5b383340302ba1455b73906e95987f8d9ccb35e2983322d23fcabe9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.1.0/aws-sso-creds-v1.1.0-linux-amd64.tar.gz"
      sha256 "5b55cc7d8dcccf4cb84c391798e6eacc3519139f543c0fd1968663a765af1e63"
    end
  end

  def install
    bin.install "aws-sso-creds"
  end
end
