# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tscli < Formula
  desc "Interact with the Tailscale API from a CLI."
  homepage "https://github.com/jaxxstorm/tscli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.1/tscli_0.0.1_darwin_amd64.tar.gz"
      sha256 "2bbce2a56708293b1e04953d145e9d5a33e61c8695d9566a1f006b5c1272b6e0"

      def install
        bin.install "tscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.1/tscli_0.0.1_darwin_arm64.tar.gz"
      sha256 "4a5aeb3f7ac4651d81065d9fffe519d040e7b7e62cd96a6a16a0474b33d63abd"

      def install
        bin.install "tscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.1/tscli_0.0.1_linux_amd64.tar.gz"
      sha256 "60ec9b16272983269ad2c141b030dfa9fce319b536d280f477c140e0b6f8f2e7"
      def install
        bin.install "tscli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.1/tscli_0.0.1_linux_arm64.tar.gz"
      sha256 "21e4511d9ca0550b9e1c97cc5cab63ad76ea2dd26f93ade9c4e8dff696083893"
      def install
        bin.install "tscli"
      end
    end
  end
end
