# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso-creds" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "e6c39167d8a1322ae4501c419e997160753bcd33235917aacb9c478b192f21e7"
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v#{version}/aws-sso-creds-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "1f10301a728034a44a4fd1aada0b721edbf39ef035efd088240e467bf9cfbb7c"
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v#{version}/aws-sso-creds-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d17712dbbf6549bd07c649c2f596f25768d466c8d3a04568e8d53802bf1ad29"
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v#{version}/aws-sso-creds-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "cbc3aeb668b5da230dec2650e2aa7ea698d5d963c24cb7577f91d29dc352c5b9"
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v#{version}/aws-sso-creds-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "aws-sso-creds"
  desc "Helper utility to get temporary credentials from AWS SSO."
  homepage "https://leebriggs.co.uk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso-creds"

  # No zap stanza required

end
