# This file was generated by GoReleaser. DO NOT EDIT.
cask "penda" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "c28945909c10f35c91f5549fd1e0708b8919b3871e3f6899f8717b6f71167c0c"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f57cc21a1363b554a82469a6095c9ebd79ecb52de5f3d267076ed1bc131de0d"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c055f555a45f63548738b71896a0b4eb54f90bbac5fa47b0dabab7776000abe"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb305ee505e5a09e4190ebe7ab6e9fb794e4aa65b4dd07ba6ffa4c79f2140f19"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "penda"
  desc "Apply Dependabot security fixes locally."
  homepage "https://leebriggs.co.uk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "penda"

  # No zap stanza required

end
