# This file was generated by GoReleaser. DO NOT EDIT.
cask "penda" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "c99b0546622a2a6707d877e7fa236179788dfb783281244fb96875ac717624df"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85b07ff5e1de12f984d4b62fabcf2ca25fc2f348275931faeaf4616965c7e143"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b85a630a6b1a4aee8769dc93f84e5a5c5a16363ae26121b3dc3617fc29857d9a"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "508b39683bc11d8b30df570a7c380d753ce5fe483a5dc4c6d7092b51414564b1"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "penda"
  desc "Apply Dependabot security fixes locally."
  homepage "https://leebriggs.co.uk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "penda"

  # No zap stanza required

end
