# This file was generated by GoReleaser. DO NOT EDIT.
cask "penda" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "4f7e455c718804bc644d95ef580b85fb10bea33b2ad93713a6024dc530319a99"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "098650b8143b7a3bf6563ed20f64126abbbde360ddbb18c1be3106e40f777743"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "234a7a25f58f02e1859c699f69bf7e296a222b5424d39cf0a652234e01959622"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4812750aea76b5bb7053097e67cbac31156bdbd21329c5e4e3b6ed315edc067"
      url "https://github.com/jaxxstorm/penda/releases/download/v#{version}/penda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "penda"
  desc "Apply Dependabot security fixes locally."
  homepage "https://leebriggs.co.uk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "penda"

  # No zap stanza required

end
