# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Helper utility to get temporary credentials from AWS SSO."
  homepage "https://leebriggs.co.uk"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.5.0/aws-sso-creds-v1.5.0-darwin-arm64.tar.gz"
      sha256 "5b2ccf9806641f156a025649e2a3f0be9abf532176c8c0a598c155cc37285db6"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.5.0/aws-sso-creds-v1.5.0-darwin-amd64.tar.gz"
      sha256 "d69f1064e1b30c0974cdee1fa3d4e175ecb482b0daba6e96d10f8cdb86f01dcc"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.5.0/aws-sso-creds-v1.5.0-linux-amd64.tar.gz"
      sha256 "529d6c33de6953de01f3fb2a06a861360e2219293be60181d7515a1f10f61c87"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.5.0/aws-sso-creds-v1.5.0-linux-arm64.tar.gz"
      sha256 "ec3e9ada97d59de2a99e8fd11180c2f54a9efdf40f4ea67c35863960a663c24d"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end
end
