# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Helper utility to get temporary credentials from AWS SSO"
  homepage "https://leebriggs.co.uk"
  version "1.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.2.0/aws-sso-creds-v1.2.0-darwin-amd64.tar.gz"
    sha256 "382539082bf1686bd7dcd3a648876d98fb26bd575fc806cba3ae5c5af0049880"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.2.0/aws-sso-creds-v1.2.0-linux-amd64.tar.gz"
    sha256 "e468112b7ff8f474442e5a6fa9e309d7a21699261881850b98aabb9655719814"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jaxxstorm/aws-sso-creds/releases/download/v1.2.0/aws-sso-creds-v1.2.0-linux-arm64.tar.gz"
    sha256 "717903fce6bbede3a34947c77d81186f5b48a5df82cff24f60920f1f150d3db0"
  end

  def install
    bin.install "aws-sso-creds"
  end
end
