# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connectme < Formula
  desc "Quickly connect to your cloud infrastructure"
  homepage "https://leebriggs.co.uk"
  version "0.0.2"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.2/connectme-v0.0.2-darwin-arm64.tar.gz"
      sha256 "1180f2d8bda01babdc53b2fa5f165d76a7ff0a5fbd26aed22abc00b0251b67ed"

      def install
        bin.install "connectme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.2/connectme-v0.0.2-darwin-amd64.tar.gz"
      sha256 "8da06783f1d57b8991f527ec16f836a50bb2a6aebb38223256655df05a00a6f2"

      def install
        bin.install "connectme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.2/connectme-v0.0.2-linux-amd64.tar.gz"
      sha256 "a7e02ae13af7727bd89f48a7cd7a7249a3f1b11298803611b255c8e61589f9f8"

      def install
        bin.install "connectme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.2/connectme-v0.0.2-linux-arm64.tar.gz"
      sha256 "a98096e83a44701c91dc1f2a69d89686ab14586f743c597d4525b3dfbe38e379"

      def install
        bin.install "connectme"
      end
    end
  end
end
