# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connecti < Formula
  desc "Quickly connect to your cloud infrastructure"
  homepage "https://leebriggs.co.uk"
  version "0.0.2"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.2/connecti-v0.0.2-darwin-arm64.tar.gz"
      sha256 "9598d1cacc5020c54137655ce0433ac05a071cd277974d7bb71dfb5138ec0b70"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.2/connecti-v0.0.2-darwin-amd64.tar.gz"
      sha256 "1807606d9d47dbaffb41d0fd6ebd301509b17c7849eb2ac78ef1e0244365296c"

      def install
        bin.install "connecti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.2/connecti-v0.0.2-linux-amd64.tar.gz"
      sha256 "02736f779ea3b6b9eaa4cc4ec99cce7396bfecf3f98a51d9249ce9e65884cc4b"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.2/connecti-v0.0.2-linux-arm64.tar.gz"
      sha256 "89ae27efdd34d5daef1a42fc79f5ddfa90a7b156787e3c748968528b0edc7ce2"

      def install
        bin.install "connecti"
      end
    end
  end
end
