# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connecti < Formula
  desc "Quickly connect to your cloud infrastructure"
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.1/connecti-v0.0.1-darwin-amd64.tar.gz"
      sha256 "619d856a451309b186361e4385865e3b3aafa0db88ca8e79cfcdb355a936a02a"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.1/connecti-v0.0.1-darwin-arm64.tar.gz"
      sha256 "07c6f447b65aeb7f404ef24dbaaa53e7409084d12afa9f6465e34c49dca15741"

      def install
        bin.install "connecti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.1/connecti-v0.0.1-linux-amd64.tar.gz"
      sha256 "681cc86f6c3b9421ce458a961475f852351e31c347bd606b3c9443e60e066ee1"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.1/connecti-v0.0.1-linux-arm64.tar.gz"
      sha256 "07c6d97770f96ab48e8e0353fd686e8e34537a23016c437679810862c74d8e09"

      def install
        bin.install "connecti"
      end
    end
  end
end
