# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connectme < Formula
  desc "Quickly connect to your cloud infrastructure"
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.1/connectme-v0.0.1-darwin-arm64.tar.gz"
      sha256 "ab970c3bcd6fb4cc84d74710ca01cc05d6d4d6945fbf835f4dfa504e944aea17"

      def install
        bin.install "connectme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.1/connectme-v0.0.1-darwin-amd64.tar.gz"
      sha256 "5fffe79151dbcbedb36bd71055bf60f28aa9a0cee14f3f37bb1538ea5e140237"

      def install
        bin.install "connectme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.1/connectme-v0.0.1-linux-amd64.tar.gz"
      sha256 "2bb0953a168a8bfda4c089449a70c6a93aa05b0d3e417b6661d0d786117c7941"

      def install
        bin.install "connectme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/connectme/releases/download/v0.0.1/connectme-v0.0.1-linux-arm64.tar.gz"
      sha256 "c2e7b5b42a942adec3c24abc0474bf19362c80d986f2718ad019bf7d2f444bdd"

      def install
        bin.install "connectme"
      end
    end
  end
end
