# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connecti < Formula
  desc "Quickly connect to your cloud infrastructure"
  homepage "https://leebriggs.co.uk"
  version "0.0.4"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.4/connecti-v0.0.4-darwin-arm64.tar.gz"
      sha256 "d81d5f56f095ae98f5b4f31cfaf20fae5ea1fb0b1d8cc0915bca8fdac9f7fe41"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.4/connecti-v0.0.4-darwin-amd64.tar.gz"
      sha256 "7d3c8b7f08dba85266da856d7a729f85f0e9d5b2ead4fb53f20cc7e6dc5b36a7"

      def install
        bin.install "connecti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.4/connecti-v0.0.4-linux-arm64.tar.gz"
      sha256 "112bc406401bd31d7501e649368b49e0baca6a204c39e449d19dc30209c6a35b"

      def install
        bin.install "connecti"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/connecti/releases/download/v0.0.4/connecti-v0.0.4-linux-amd64.tar.gz"
      sha256 "58d893f7896b6f690e69144bd9aae1307a34de049f096097f6c5e5592271e1d1"

      def install
        bin.install "connecti"
      end
    end
  end
end
