# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnstrace < Formula
  desc "Trace DNS delegation and explain resolution failures."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/jaxxstorm/dnstrace/releases/download/v0.0.1/dnstrace-v0.0.1-darwin-amd64.tar.gz"
      sha256 "7cd6899c3ed353e7c88c9958aed21cfd2cf18451ff7ee84249465d301715189c"

      def install
        bin.install "dnstrace"
      end
    end
    on_arm do
      url "https://github.com/jaxxstorm/dnstrace/releases/download/v0.0.1/dnstrace-v0.0.1-darwin-arm64.tar.gz"
      sha256 "baccab8aae3d377baf13fa4254d14a8857d27ddaa9ad5b26cbbb15f71d930bda"

      def install
        bin.install "dnstrace"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/dnstrace/releases/download/v0.0.1/dnstrace-v0.0.1-linux-amd64.tar.gz"
        sha256 "b6b5e5942298050e55dfa764f38b6a57ed536f9bd75b1a66068ed11814fbaff2"

        def install
          bin.install "dnstrace"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/dnstrace/releases/download/v0.0.1/dnstrace-v0.0.1-linux-arm64.tar.gz"
        sha256 "b9a33b0452024538102bc2218e42248815fc66b26b585ba34004fe8801f7b7ac"

        def install
          bin.install "dnstrace"
        end
      end
    end
  end
end
