# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grass < Formula
  desc "Search for keywords on social media sites."
  homepage "https://leebriggs.co.uk"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/jaxxstorm/grass/releases/download/v0.0.3/grass_Darwin_x86_64.tar.gz"
      sha256 "ded5788f83caf9899adb7eda728debfc2b331e1fe492b9d349572c2c6150d69d"

      def install
        bin.install "grass"
      end
    end
    on_arm do
      url "https://github.com/jaxxstorm/grass/releases/download/v0.0.3/grass_Darwin_arm64.tar.gz"
      sha256 "35cfdf26db269f827fb04ab91b0424331ee1a719931c56a9d54775bbba068b74"

      def install
        bin.install "grass"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/grass/releases/download/v0.0.3/grass_Linux_x86_64.tar.gz"
        sha256 "c4a2822d677a8580f9feb12e03ffdccee400727a1a0b6b5c1e9d16b55d2730e3"

        def install
          bin.install "grass"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/grass/releases/download/v0.0.3/grass_Linux_arm64.tar.gz"
        sha256 "7d694cb2cb9f66d9601b518459d56aa300f7452d03b523aa83a484dd530a546d"

        def install
          bin.install "grass"
        end
      end
    end
  end
end
