# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Met < Formula
  desc "Dynamically render prometheus metrics in your terminal."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/met/releases/download/v0.0.1/met-v0.0.1-darwin-amd64.tar.gz"
      sha256 "173aa21db27df39558c61dc8e35942d252a42fd935c9daafdf41966adc673d2e"

      def install
        bin.install "met"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/met/releases/download/v0.0.1/met-v0.0.1-darwin-arm64.tar.gz"
      sha256 "8d9ad012aa047fe0c918addfd38dbf88f1b445db50e1e0ef7f9486ac1712b817"

      def install
        bin.install "met"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/met/releases/download/v0.0.1/met-v0.0.1-linux-amd64.tar.gz"
        sha256 "a4748bd4c21c4707403b7439329bf8553e8ef5614c84e74d7ca82c935ee16700"

        def install
          bin.install "met"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/met/releases/download/v0.0.1/met-v0.0.1-linux-arm64.tar.gz"
        sha256 "aae2ae2141d0ce9d18ca56c1a20b2867243c27928f15cdf740357c5a9aed94e7"

        def install
          bin.install "met"
        end
      end
    end
  end
end
