# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Met < Formula
  desc "Dynamically render prometheus metrics in your terminal."
  homepage "https://leebriggs.co.uk"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/met/releases/download/v0.0.3/met-v0.0.3-darwin-amd64.tar.gz"
      sha256 "c6217f0f80ffa5447f296048bbdf9663bd2eb0cb56ce1b2276868a7fd233f5db"

      def install
        bin.install "met"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/met/releases/download/v0.0.3/met-v0.0.3-darwin-arm64.tar.gz"
      sha256 "31fdc5743bb1219e61aebb570deae0f25001a26bdd7391fc5a290e9f71a42ce1"

      def install
        bin.install "met"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/met/releases/download/v0.0.3/met-v0.0.3-linux-amd64.tar.gz"
        sha256 "4b17552a941931d70759291d7ac58b44311534d3e443da0ecf6dc76372ca7218"

        def install
          bin.install "met"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/met/releases/download/v0.0.3/met-v0.0.3-linux-arm64.tar.gz"
        sha256 "32b4146fdd19dece4e9016edea3b28912f441b32de615f8d0c59ab8d2ea2eaa7"

        def install
          bin.install "met"
        end
      end
    end
  end
end
