# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pedloy < Formula
  desc "Search for keywords on social media sites."
  homepage "https://leebriggs.co.uk"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/jaxxstorm/pedloy/releases/download/v0.0.2/pedloy_Darwin_x86_64.tar.gz"
      sha256 "0f87d7d855562a09573b445befdd32a0dda67293858a1c998a90a25246823238"

      def install
        bin.install "pedloy"
      end
    end
    on_arm do
      url "https://github.com/jaxxstorm/pedloy/releases/download/v0.0.2/pedloy_Darwin_arm64.tar.gz"
      sha256 "e3d5954ae12f476b104d5c843f900c183ba9fa7f566771674370cc0f07190066"

      def install
        bin.install "pedloy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/pedloy/releases/download/v0.0.2/pedloy_Linux_x86_64.tar.gz"
        sha256 "98bec7064025131cc26f574433a0eb6438b285dd66508109648e7338349db1a5"

        def install
          bin.install "pedloy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/pedloy/releases/download/v0.0.2/pedloy_Linux_arm64.tar.gz"
        sha256 "1fabf1e8e8ee96214e94e73b835349067690e9dcc76c77ab540b8e6711ed3357"

        def install
          bin.install "pedloy"
        end
      end
    end
  end
end
