# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "A logging and monitoring proxy based on Tailscale server and funnel."
  homepage "https://leebriggs.co.uk"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.7/portal-v0.0.7-darwin-amd64.tar.gz"
      sha256 "15a5d348c141c44f4114271ffedf77bc3f332ab5cfc44b379b66c55d3e836f4a"

      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.7/portal-v0.0.7-darwin-arm64.tar.gz"
      sha256 "439956e3e45d6c85f3964b44ddcb80eb4e780622420addb09dfc6c2bed92ddc0"

      define_method(:install) do
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.7/portal-v0.0.7-linux-amd64.tar.gz"
      sha256 "5bfdda35d7e63d0e71267e6fdf113d62a3410ceda1228a9a2153fc75b7991478"
      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.7/portal-v0.0.7-linux-arm64.tar.gz"
      sha256 "32a79140d76247b5ecac9d6d084146adc4930f1947a2bdeccded4fe29dc3a012"
      define_method(:install) do
        bin.install "portal"
      end
    end
  end
end
