# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "A logging and monitoring proxy based on Tailscale server and funnel."
  homepage "https://leebriggs.co.uk"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.5/portal-v0.0.5-darwin-amd64.tar.gz"
      sha256 "d7541f6e334ae3ef25c3be018a563140c502c98bcca5058ff156a93cd612c243"

      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.5/portal-v0.0.5-darwin-arm64.tar.gz"
      sha256 "1e473720e0224798d1c4d1e8602e365ab4164ae0db3960981a16d231b29f33d8"

      define_method(:install) do
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.5/portal-v0.0.5-linux-amd64.tar.gz"
      sha256 "84f7cc9029a29927c6d7b822e55379ecc7e269fc25a4d1395f57b40dee199acd"
      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/portal/releases/download/v0.0.5/portal-v0.0.5-linux-arm64.tar.gz"
      sha256 "2409cff1c288739ffe9ea544a515083dd8e85d7cce6bc80b64c3c25ba8dfe619"
      define_method(:install) do
        bin.install "portal"
      end
    end
  end
end
