# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxyt < Formula
  desc "Easily proxy the Tailscale login API for blocked networks."
  homepage "https://github.com/jaxxstorm/proxyt"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.5/proxyt_0.0.5_darwin_amd64.tar.gz"
      sha256 "7af8e58a23adf45ec87020a05b64b89c66f708c9bcf6f04379fbd20114497b8a"

      def install
        bin.install "proxyt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.5/proxyt_0.0.5_darwin_arm64.tar.gz"
      sha256 "c005fc3201d78b216bfcbd7c10deb7a29864e4c23183660a387eb0be876201b1"

      def install
        bin.install "proxyt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.5/proxyt_0.0.5_linux_amd64.tar.gz"
      sha256 "7edf1252d83a000e9925400f447316eff23c92470897236f005c499a35868a5d"
      def install
        bin.install "proxyt"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.5/proxyt_0.0.5_linux_arm64.tar.gz"
      sha256 "a5dd54653b0c15278895dcf9d138a5fdc2e8dddf7c7857566b4d31b8f7fb5178"
      def install
        bin.install "proxyt"
      end
    end
  end
end
