# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxyt < Formula
  desc "Easily proxy the Tailscale login API for blocked networks."
  homepage "https://github.com/jaxxstorm/proxyt"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.7/proxyt_0.0.7_darwin_amd64.tar.gz"
      sha256 "fea8700bc09b8b10bfc1e6a1c0d584aa2ccfd11bf5df88331a1124c8dbec3493"

      define_method(:install) do
        bin.install "proxyt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.7/proxyt_0.0.7_darwin_arm64.tar.gz"
      sha256 "50b611ca426c13c5c0e65c84b5e3c81a6919a10af0efd8df6ad40740059104a2"

      define_method(:install) do
        bin.install "proxyt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.7/proxyt_0.0.7_linux_amd64.tar.gz"
      sha256 "ac08ac4c63f2405c954d16b21253303525f52455123cdc1b50b6a4fa14a71c10"
      define_method(:install) do
        bin.install "proxyt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/proxyt/releases/download/v0.0.7/proxyt_0.0.7_linux_arm64.tar.gz"
      sha256 "bcec44c88ab620c0c1c79ed100549046f1b5729126e5c523c4605c338bd465f6"
      define_method(:install) do
        bin.install "proxyt"
      end
    end
  end
end
