# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stunner < Formula
  desc "A CLI tool to detect NAT type."
  homepage "https://leebriggs.co.uk"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.5/stunner-v0.0.5-darwin-amd64.tar.gz"
      sha256 "393ba6e54965c42f70081e4fa82b526ed7792eefe23ca96344b19e6c3518108c"

      def install
        bin.install "stunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.5/stunner-v0.0.5-darwin-arm64.tar.gz"
      sha256 "5f0e47ff74ff9f7a4257374dda33698e788d973bb2df2efbffb21621ee9a083e"

      def install
        bin.install "stunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.5/stunner-v0.0.5-linux-amd64.tar.gz"
        sha256 "c1f907f14511d45a91dcf87626dc334079c22f4b7752280ffbd0b4077f748123"

        def install
          bin.install "stunner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.5/stunner-v0.0.5-linux-arm64.tar.gz"
        sha256 "8aaa8b7c3103fb3c54a05300b5ccfe63594139eb5aaf5786265099a3a9cb0929"

        def install
          bin.install "stunner"
        end
      end
    end
  end
end
