# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stunner < Formula
  desc "A CLI tool to detect NAT type."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.1/stunner-v0.0.1-darwin-amd64.tar.gz"
      sha256 "301daf122841adb19e529318fb84c28e5190456bd9ffcc55a3402baab7f621d7"

      def install
        bin.install "stunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.1/stunner-v0.0.1-darwin-arm64.tar.gz"
      sha256 "2e637e88ad1177595e5a10266709bf5e719ff21b2fa2414e15fa4b5d0fa8acd6"

      def install
        bin.install "stunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.1/stunner-v0.0.1-linux-amd64.tar.gz"
        sha256 "cc463b668bab9d8a2cf92389415d6197b15f248348d21a3f8136a46d9a5063f7"

        def install
          bin.install "stunner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.1/stunner-v0.0.1-linux-arm64.tar.gz"
        sha256 "27ce1575512a76abf5b9c7d40098fea9d2f84349471dced4426bd414f0c5559f"

        def install
          bin.install "stunner"
        end
      end
    end
  end
end
