# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stunner < Formula
  desc "A CLI tool to detect NAT type."
  homepage "https://leebriggs.co.uk"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.6/stunner-v0.0.6-darwin-amd64.tar.gz"
      sha256 "b735b2f5b37c5049328a93e8ddf54bfa603aeab307558fa03c8cf2732c13042c"

      def install
        bin.install "stunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.6/stunner-v0.0.6-darwin-arm64.tar.gz"
      sha256 "9b4819bc18a259a94a47a0f838c955054a711e82ba51c75fcbef3c46f86db4c7"

      def install
        bin.install "stunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.6/stunner-v0.0.6-linux-amd64.tar.gz"
        sha256 "a52ed36a2bd3ed18ee419a300dc1ab3ca07713b9c74000223bb30356a14f1293"

        def install
          bin.install "stunner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/stunner/releases/download/v0.0.6/stunner-v0.0.6-linux-arm64.tar.gz"
        sha256 "4640c91d48a4cb3eb6c0f3cf7e6c31d1541836e8fa2b59b975123ba26b17358e"

        def install
          bin.install "stunner"
        end
      end
    end
  end
end
