# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailscaleMcpProxy < Formula
  desc "An MCP proxy server that works over Tailscale."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tailscale-mcp-proxy/releases/download/v0.0.1/tailscale-mcp-proxy-v0.0.1-darwin-amd64.tar.gz"
      sha256 "49406414a9d613e70a0c86532de5c6c6e45bb8eb8c4b34c9b6549307898b9271"

      def install
        bin.install "tailscale-mcp-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tailscale-mcp-proxy/releases/download/v0.0.1/tailscale-mcp-proxy-v0.0.1-darwin-arm64.tar.gz"
      sha256 "e76eaf5e59c7ab4731f27e8f8f4b4061722f4488451f0100b189bc354b212cf4"

      def install
        bin.install "tailscale-mcp-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tailscale-mcp-proxy/releases/download/v0.0.1/tailscale-mcp-proxy-v0.0.1-linux-amd64.tar.gz"
      sha256 "58940f3134009997bd7547b8f6217b0ec897834a4932ff6679cba842eb8e14ba"
      def install
        bin.install "tailscale-mcp-proxy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tailscale-mcp-proxy/releases/download/v0.0.1/tailscale-mcp-proxy-v0.0.1-linux-arm64.tar.gz"
      sha256 "3b7c3f24a18e04e3ee5b454c43f6deae7961e11ed2fd0ac569862d875ae72ed2"
      def install
        bin.install "tailscale-mcp-proxy"
      end
    end
  end
end
