# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailscaleMcp < Formula
  desc "An MCP server for Tailscale."
  homepage "https://leebriggs.co.uk"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tailscale-mcp/releases/download/v0.0.11/tailscale-mcp-v0.0.11-darwin-amd64.tar.gz"
      sha256 "87d811a8d2d03e1b8f464f92b723c2bf41c0fa786106f7a57c7885375d5a581d"

      define_method(:install) do
        bin.install "tailscale-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tailscale-mcp/releases/download/v0.0.11/tailscale-mcp-v0.0.11-darwin-arm64.tar.gz"
      sha256 "ebfa8825232efaf5387207a79b2df3d693f127e8e0be0edb6fd9186d816b9dd4"

      define_method(:install) do
        bin.install "tailscale-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tailscale-mcp/releases/download/v0.0.11/tailscale-mcp-v0.0.11-linux-amd64.tar.gz"
      sha256 "9a6de99fedc39b7ff5bb3ec36b6e81aa5b118543faf4fe0cf9e601a5f6d3114f"
      define_method(:install) do
        bin.install "tailscale-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tailscale-mcp/releases/download/v0.0.11/tailscale-mcp-v0.0.11-linux-arm64.tar.gz"
      sha256 "d9d9ff7ca07776d5e1366e58fb681b95033d6bd0181d738badf21e6688302eef"
      define_method(:install) do
        bin.install "tailscale-mcp"
      end
    end
  end
end
