# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailscaleCleanup < Formula
  desc "A simple CLI tool to delete disconnected devices from a Tailnet"
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tailscale-cleanup/releases/download/v0.0.1/tailscale-cleanup_Darwin_x86_64.tar.gz"
      sha256 "801bf0054ab778790f44f830ba958272863277bba03d3e32eb9d1915f5dd8fc8"

      def install
        bin.install "tailscale-cleanup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tailscale-cleanup/releases/download/v0.0.1/tailscale-cleanup_Darwin_arm64.tar.gz"
      sha256 "a8cb9e2f1021b1d3adc9c81137038cfd9e903478eecf043f2e5c5071783d8d8c"

      def install
        bin.install "tailscale-cleanup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/tailscale-cleanup/releases/download/v0.0.1/tailscale-cleanup_Linux_x86_64.tar.gz"
        sha256 "e123489da49f5dc78dbf46879ee69bb7cc0d08afd1187bf2636f94b63515078f"

        def install
          bin.install "tailscale-cleanup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaxxstorm/tailscale-cleanup/releases/download/v0.0.1/tailscale-cleanup_Linux_arm64.tar.gz"
        sha256 "686d779d90f0759200c6092050c16dda3c6bfbd2062bdab5d3f1d21ffd7db5b4"

        def install
          bin.install "tailscale-cleanup"
        end
      end
    end
  end
end
