# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgate < Formula
  desc "A logging and monitoring proxy based on Tailscale server and funnel."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tgate/releases/download/v0.0.1/tgate-v0.0.1-darwin-amd64.tar.gz"
      sha256 "fec2a0aa4efc303dd2ca8853e3d475e682d50120d30fd46b26f6c2d9c58bec45"

      def install
        bin.install "tgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tgate/releases/download/v0.0.1/tgate-v0.0.1-darwin-arm64.tar.gz"
      sha256 "c0ce826472bdd335baeaadab2be2ea3784bd15a5e833a17e16e301286e70ab93"

      def install
        bin.install "tgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tgate/releases/download/v0.0.1/tgate-v0.0.1-linux-amd64.tar.gz"
      sha256 "2e4439420c425db0f8eedd869efead1f42604b360e7ae0773c501c11fec0fc01"
      def install
        bin.install "tgate"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tgate/releases/download/v0.0.1/tgate-v0.0.1-linux-arm64.tar.gz"
      sha256 "a902171443af3c21f9a8c79c2a3137b233f7f010373ad3bc22e8f52f38f1c9b8"
      def install
        bin.install "tgate"
      end
    end
  end
end
