# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thresher < Formula
  desc "Decode Tailscale debug captures and analyze packet streams."
  homepage "https://github.com/jaxxstorm/thresher"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/thresher/releases/download/v0.0.1/thresher_0.0.1_darwin_amd64.tar.gz"
      sha256 "585ed5b80ecc0235049b45997c64c813de85ec4d3f47e5cb012d55e154106f6b"

      define_method(:install) do
        bin.install "thresher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/thresher/releases/download/v0.0.1/thresher_0.0.1_darwin_arm64.tar.gz"
      sha256 "95879597e70aa05bdac7312b8cc3f0131fb50c9e0400996a8cdae8feffd641d5"

      define_method(:install) do
        bin.install "thresher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/thresher/releases/download/v0.0.1/thresher_0.0.1_linux_amd64.tar.gz"
      sha256 "32cd982f31c4e5983ad70739fcbf122b30b2b8716007f92c4e59a121ce631c3a"
      define_method(:install) do
        bin.install "thresher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/thresher/releases/download/v0.0.1/thresher_0.0.1_linux_arm64.tar.gz"
      sha256 "c831c95598b4d1401b9e98fdcde225591a07c46c8de93b0cce4580300377834e"
      define_method(:install) do
        bin.install "thresher"
      end
    end
  end
end
