# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tscli < Formula
  desc "Interact with the Tailscale API from a CLI."
  homepage "https://github.com/jaxxstorm/tscli"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.9/tscli_0.0.9_darwin_amd64.tar.gz"
      sha256 "168ce870b7637f74ed0ed648aa4459875ea2be0a76fe428dd9512eea8e86c66d"

      def install
        bin.install "tscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.9/tscli_0.0.9_darwin_arm64.tar.gz"
      sha256 "7ed5ca2da1d6a34ca610866aa710a5fd018845d29859846b9c434c181d79c2aa"

      def install
        bin.install "tscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.9/tscli_0.0.9_linux_amd64.tar.gz"
      sha256 "67de792aa3826e0a2bac8fd76631c71c54d4334cd6d7f30cd41e4f61f23733f4"
      def install
        bin.install "tscli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/tscli/releases/download/v0.0.9/tscli_0.0.9_linux_arm64.tar.gz"
      sha256 "9b6cba0afaf9f932bd7ac1354ea0b7b7f168a8986728f71cb16047f206a3382a"
      def install
        bin.install "tscli"
      end
    end
  end
end
