# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vers < Formula
  desc "Calculate versions from Git repositories."
  homepage "https://leebriggs.co.uk"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaxxstorm/vers/releases/download/v0.0.1/vers-v0.0.1-darwin-amd64.tar.gz"
      sha256 "f742db23dde0a7e336d90892f17d70399f8ca38fc02e599135cd63bbef27188e"

      def install
        bin.install "vers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaxxstorm/vers/releases/download/v0.0.1/vers-v0.0.1-darwin-arm64.tar.gz"
      sha256 "b15125fe8fda349f2ea29a92ec9972092fd0cc94ed8cc6d922aff86caa01899a"

      def install
        bin.install "vers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/vers/releases/download/v0.0.1/vers-v0.0.1-linux-amd64.tar.gz"
      sha256 "68a6d6b7abe3efa3a6087c6e0d08a5fda868d1c24d7979f6f6e621efbc3f1dfd"
      def install
        bin.install "vers"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaxxstorm/vers/releases/download/v0.0.1/vers-v0.0.1-linux-arm64.tar.gz"
      sha256 "f5d7efa8fb2d8fbb7a99b409ff6802e2d1f344401fc2326dfa5564dffc67b7dc"
      def install
        bin.install "vers"
      end
    end
  end
end
